### ISSUE TITLE
FRLG TID/SID Calculation Issue

### ISSUE THREAD

**Issue by papajefe** [E-Sh4rk/EmeraldACE_web#26]
Had a user submit an issue with FRLG "Change TID SID (Grab ACE)."

The values inputted were:
```
TID = 0x0077
SID = 0x0077
```
But the output yielded a TID/SID of 00120 in game (0x0078)

I tested with 0x0078, and got 00121 in game.

Checked the output and it looks like the ? operator is doing some dumb math somewhere.

```
MOVS R11, #0xA1
SBC R11, R11, #0x29
```

Should be 

```
MOVS R11, #0xA1
SBC R11, R11 #0x2A
```

**Comment by E-Sh4rk** [comment]
Hello,

I think the issue we're having here is more subtle. The ACE code generator assumes the Carry flag of the CPSR register is 0.
It means that SBC operations will always do an additional -1 (and ADC operations will just add the specified amount).
This is why the generator does `SBC R11, R11, #0x29` instead of `SBC R11, R11 #0x2A`.
However if this assumption about the CPSR register is not verified, then we get the wrong value.

Can you test the code again but with the first command `sbcs r12, r15, #0xd100` changed to `sbc r12, r15, #0xd100`?
I am not sure exactly how `sbcs` changes the carry flag but my guess would be that it sets it to 1. Better avoid using `sbcs` and use `sbc` instead so that it does not change the CPSR register.

**Comment by E-Sh4rk** [comment]
I have changed the first command accordingly.
Let me know when you have some feedback about that.
